### ISSUE TITLE
There is a problem accessing nexus.libreplan.org to get the jasperreport dependency

### ISSUE THREAD

**Issue by 4mig4** [LibrePlan/jasperreport#3]
There is a problem accessing nexus.libreplan.org with "master"

http://nexus.libreplan.org/nexus/content/repositories/thirdparty-libreplan16/com/libreplan/java/zk/components/jasperreportcomponent/1.1/jasperreportcomponent-1.1.pom. Return code is: 502 , ReasonPhrase:Bad Gateway.

**Comment by 4mig4** [comment]
Actually it is the load balancer that is totally broken , nginx is 502 on some request because some hosts behind it are dead or not answering.

**Comment by 4mig4** [comment]
Actually that is just that the file is simply not there! Can anyone put it there so I can complete my FreeBSD build ?

**Comment by kwoot** [comment]
Nexus restarted. Should work now. Thanks for letting me know.

**Comment by 4mig4** [comment]
Why is there no issue reporting capabilities in the libreplan project on github ?
