### ISSUE TITLE
Libreplan issue reporting

### ISSUE THREAD

**Issue by 4mig4** [LibrePlan/jasperreport#4]
Why is there no "issues" tab in the Libreplan github project ?

**Comment by kwoot** [comment]
I prefer to focus on bugs.libreplan.org.

**Comment by 4mig4** [comment]
Ok so my builds do not work on FreeBSD and I have no clues why.

**Comment by kwoot** [comment]
LibrePlan on FreeBSD would be very cool, I have to say. But you would be the first to try afaik.

**Comment by 4mig4** [comment]
I got it to build on FreeBSD 11p9 but libreplan needs to change pom.xml for :  
https://github.com/jgettext/gettext-commons.git
https://github.com/rlf/maven-gettext-plugin.git

because googlecode does not exist anymore.

I suspect your github codebase is not a mirror of your internal code base. Otherwise your code base would never build for version 1.4.1. because of the above.

**Comment by kwoot** [comment]
There is no internal code base. Github is the de facto standard. Yes, 1.4.1 does not build but head of the 1.4.1 branch should build correctly. If not, please submit a PR on branches libreplan-1.4, libreplan-1.5 and master and I will gladly merge.

**Comment by 4mig4** [comment]
OK for now I need it to run ASAP, already spent 3 days on this on FreeBSD without final result. So now I will just try to use a Ubuntu install. Will come back to the FreeBSD install and packaging later.

**Comment by kwoot** [comment]
use ubuntu 14.04 lts, add ppa, install. done. check tomcat memory.

**Comment by 4mig4** [comment]
used ubuntu 16.04.02 , tomcat8 and postgres external server.

does not work , DB corrupted it seems, which version of the install.sql should be used ? 
Trying to start it bound to a real FQDN and not localhost.

**Comment by kwoot** [comment]
Read my former entry.

**Comment by 4mig4** [comment]
Did read it, not going to use 14.04 it is obsolete aditionally openjdk8 and tomcat8 should work.

**Comment by 4mig4** [comment]
W: The repository 'http://ppa.launchpad.net/libreplan/ppa/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/libreplan/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found

**Comment by 4mig4** [comment]
I think you should update your ppa  to 16.04.02 and sign it.

**Comment by kwoot** [comment]
1.4.2 will at some time be released for 16.04. 14.04 is at this time still a maintained release of production quality. Since LibrePlan is fully open source you are of course free to try other combinations, at your own peril of course.

**Comment by 4mig4** [comment]
mvn -Pprod,postgresql -DskipTests clean install , does not seems to produce a usable .war
